const GET_LIST_CAMPAIGN_SUCCESS = 'ListCampaign/GET_LIST_CAMPAIGN_SUCCESS';
const GET_LIST_CAMPAIGN_FAIL = 'ListCampaign/GET_LIST_CAMPAIGN_FAIL';

export {
    GET_LIST_CAMPAIGN_SUCCESS,
    GET_LIST_CAMPAIGN_FAIL,
}